name: MLforPhysicists
channels:
  - defaults
dependencies:
  - black=19.10b0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - keras=2.3.1
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandoc=2.2.3.2
  - python=3.7.7
  - scipy=1.4.1
  - sympy=1.5.1
  - tensorflow=2.1.0
